openapi: 3.0.0
info:
  title: Backend Aula API
  version: 1.0.0
  description: |
    Aqui você encontra a documentação dos endpoints. Para serem utilizados em seu desenvolvimento frontend

    URL: https://backend-completo.vercel.app

    Qualquer dúvida, consulte o professor.
servers:
  - url: https://backend-completo.vercel.app
tags:
  - name: Abertos
    description: Endpoints para acesso sem login
  - name: Área administrativa Categorias
    description: Endpoints para acesso através de Token
  - name: Área administrativa Produtos
    description: Endpoints para acesso através de Token
  - name: Área administrativa Vendas
    description: Endpoints para acesso através de Token    
paths:
  /app/registrar:
    post:
      tags:
        - Abertos
      summary: Registrar usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                usuario:
                  type: string
                  description: Usuário RA do aluno
                senha:
                  type: string
                  description: Senha (não será criptografada)
                confirma:
                  type: string
                  description: Confirmação da senha
              required:
                - usuario
                - senha
                - confirma
      responses:
        '200':
          description: Usuário registrado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  usuario:
                    type: string
                  senha:
                    type: string
                  id:
                    type: string
        '400':
          description: Erro ao registrar usuário
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /app/login:
    post:
      tags:
        - Abertos
      summary: Login do usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                usuario:
                  type: string
                  description: Usuário RA do aluno
                senha:
                  type: string
                  description: Senha (não será criptografada)
              required:
                - usuario
                - senha
      responses:
        '200':
          description: Login bem-sucedido
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Erro ao fazer login
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /app/produtos/{usuario}/{nome_produto}:
    get:
      tags:
        - Abertos
      summary: Listar Produtos
      parameters:
        - in: path
          name: usuario
          schema:
            type: string
          required: true
          description: Usuario responsável pelo trabalho (usuario criado para o login na área administrativa)
        - in: path
          name: nome_produto
          schema:
            type: string
          description: Nome do produto
      responses:
        '200':
          description: Lista de produtos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    usuario:
                      type: string
                    nome:
                      type: string
                    quantidade:
                      type: integer
                    preco:
                      type: number
                    categoria:
                      type: string
                      description: Categoria do produto
                    descricao:
                      type: string
                    imagem:
                      type: string
                    __v:
                      type: integer
  /app/produtos/:
    post:
      tags:
        - Área administrativa Produtos
      summary: Novo Produto
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                quantidade:
                  type: integer
                preco:
                  type: number
                categoria:
                  type: string
                  description: Categoria do produto (opcional)
                descricao:
                  type: string
                imagem:
                  type: string
              required:
                - nome
                - quantidade
                - preco
                - descricao
                - imagem
      responses:
        '200':
          description: Produto criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  nome:
                    type: string
                  quantidade:
                    type: integer
                  preco:
                    type: number
                  categoria:
                    type: string
                  descricao:
                    type: string
                  imagem:
                    type: string
                  __v:
                    type: integer
        '400':
          description: Erro ao criar produto
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    put:
      tags:
        - Área administrativa Produtos
      summary: Atualizar Produto
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                nome:
                  type: string
                quantidade:
                  type: integer
                preco:
                  type: number
                categoria:
                  type: string
                  description: Categoria do produto (opcional)
                descricao:
                  type: string
                imagem:
                  type: string
              required:
                - id
                - nome
                - quantidade
                - preco
                - descricao
                - imagem
      responses:
        '200':
          description: Produto atualizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  nome:
                    type: string
                  quantidade:
                    type: integer
                  preco:
                    type: number
                  categoria:
                    type: string
                  descricao:
                    type: string
                  imagem:
                    type: string
        '400':
          description: Erro ao atualizar produto
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
    delete:
      tags:
        - Área administrativa Produtos
      summary: Excluir Produto
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              required:
                - id
      responses:
        '200':
          description: Produto excluído com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '400':
          description: Erro ao excluir produto
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /app/categorias:
    get:
      tags:
        - Área administrativa Categorias
      summary: Listar Categorias
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: nome_categoria
          schema:
            type: string
          description: Nome da categoria para filtro (opcional)
      responses:
        '200':
          description: Lista de categorias
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    usuario:
                      type: string
                    nome:
                      type: string
    post:
      tags:
        - Área administrativa Categorias
      summary: Criar Nova Categoria
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome_categoria:
                  type: string
                  description: Nome da categoria
              required:
                - nome_categoria
      responses:
        '200':
          description: Categoria criada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  usuario:
                    type: string
                  nome:
                    type: string
    put:
      tags:
        - Área administrativa Categorias
      summary: Atualizar Categoria
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                nome_categoria:
                  type: string
              required:
                - id
                - nome_categoria
      responses:
        '200':
          description: Categoria atualizada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  nome:
                    type: string
    delete:
      tags:
        - Área administrativa Categorias
      summary: Excluir Categoria
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
              required:
                - id
      responses:
        '200':
          description: Categoria excluída com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /app/venda:
    post:
      tags:
        - Abertos
      summary: Criar Nova Venda
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nomeCliente:
                  type: string
                usuario:
                  type: string
                data:
                  type: string
                  format: date
                produtos:
                  type: array
                  items:
                    type: object
                    properties:
                      nome:
                        type: string
                      quantidade:
                        type: integer
                      preco:
                        type: number
              required:
                - nomeCliente
                - data
                - produtos
                - usuario
      responses:
        '200':
          description: Venda criada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  _id:
                    type: string
                  nomeCliente:
                    type: string
                  data:
                    type: string
                    format: date
                  produtos:
                    type: array
                    items:
                      type: object
                      properties:
                        nome:
                          type: string
                        quantidade:
                          type: integer
                        preco:
                          type: number
    get:
      tags:
        - Área administrativa Vendas
      summary: Listar Vendas
      parameters:
        - in: query
          name: id
          schema:
            type: string
          description: ID da venda para filtro (opcional)
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Listar de vendas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                    usuario:
                      type: string
                    nomeCliente:
                      type: string
                    data:
                      type: string
                      format: date
                    produtos:
                      type: array
                      items:
                        type: object
                        properties:
                          nome:
                            type: string
                          quantidade:
                            type: integer
                          preco:
                            type: number
    delete:
      tags:
        - Área administrativa Vendas
      summary: Excluir Venda
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID da venda a ser excluída
      security: 
        - bearerAuth: []
      responses:
        '200':
          description: Venda excluída com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /app/limpar:
    get:
      summary: Limpar todas as TABELAS do usuário de login
      description: Remove todos os dados das tabelas categorias, produtos, usuário e venda para o usuário autenticado. Isso para inicar um novo teste
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Tabelas limpas com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensagem:
                    type: string
                    example: "Tabelas limpas com sucesso para o usuário."
        '400':
          description: Erro de autenticação
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: "Usuário não autenticado."
        '500':
          description: Erro interno do servidor
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                    example: "Erro ao limpar tabelas."
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
